use_frameworks!

target 'EEUISDK_Example' do
    #pod 'EEUISDK', :path => '../'
  pod 'EEUISDK', '0.1.0'

  target 'EEUISDK_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
